version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: datawow_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-datawow_test}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - datawow_network

networks:
  datawow_network:
    driver: bridge

volumes:
  postgres_data:
